# Generated by Django 5.1.6 on 2025-02-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_game_current_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='call_friend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='skip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='two_answers',
            field=models.BooleanField(default=False),
        ),
    ]
